# PBS configuration
queue: normal
project: x77
walltime: 1:00:00
jobname: cm_1440x1080-system_test
ncpus: 1248

shortpath: /short/v45

# Model configuration
model: access
submodels:
    - name: coupler
      model: oasis
      input: oasis_cm_1440x1080
      ncpus: 0

    - name: atmosphere
      model: um
      exe: um7.3x
      input: um
      ncpus: 96

    - name: ocean
      model: mom
      exe: fms_ACCESS-CM.x
      input: mom_cm_1440x1080
      ncpus: 960
      build:
          path_to_build_command: exp
          command: './MOM_compile.csh --platform nci --type ACCESS-CM'
          exec_path: exec/nci/ACCESS-CM/

    - name: ice
      model: cice
      exe: cice_access-cm_1440x1080_192p.exe
      input: cice_cm_1440x1080
      ncpus: 192
      build:
          exec_path: build_access-cm_1440x1080_192p
          command: 'make access-hcm'

calendar:
    runtime:
        years: 0
        months: 0
        days: 1

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
collate_mem: 16GB
qsub_flags: -lother=hyperthread
