# PBS configuration
queue: normal
project: v45
walltime: 05:00:00
jobname: cm_360x300-test
ncpus: 64

shortpath: /short/v45

# Model configuration
model: access
submodels:
    - name: coupler
      model: oasis
      input: oasis_cm
      ncpus: 0

    - name: atmosphere
      model: um
      exe: um7.3.dbg.exe
      exe_prefix: -x LD_PRELOAD=/home/599/nah599/usr/local/lib/valgrind/libmpiwrap-amd64-linux.so /home/599/nah599/usr/local/bin/valgrind --main-stacksize=2000000000 --max-stackframe=2000000000 --error-limit=no --gen-suppressions=all --suppressions=/home/599/nah599/more_home/access-tests/valgrind_suppressions.txt
      input: um
      ncpus: 32

    - name: ocean
      model: mom
      exe: fms_ACCESS-CM.x
      exe_prefix: -x LD_PRELOAD=/home/599/nah599/usr/local/lib/valgrind/libmpiwrap-amd64-linux.so /home/599/nah599/usr/local/bin/valgrind --main-stacksize=2000000000 --max-stackframe=2000000000 --error-limit=no --gen-suppressions=all --suppressions=/home/599/nah599/more_home/access-tests/valgrind_suppressions.txt
      input: mom
      ncpus: 16
      build:
          path_to_build_command: exp
          command: './MOM_compile.csh --platform nci --type ACCESS-CM --debug'
          exec_path: exec/nci/ACCESS-CM/

    - name: ice
      model: cice
      exe: cice_access-cm_360x300_6p.exe
      exe_prefix: -x LD_PRELOAD=/home/599/nah599/usr/local/lib/valgrind/libmpiwrap-amd64-linux.so /home/599/nah599/usr/local/bin/valgrind --main-stacksize=2000000000 --max-stackframe=2000000000 --error-limit=no --gen-suppressions=all --suppressions=/home/599/nah599/more_home/access-tests/valgrind_suppressions.txt
      input: cice
      ncpus: 6
      build:
          exec_path: build_access-cm_360x300_6p
          command: './bld/build.sh nci access-cm 360x300 unit_testing'

calendar:
    runtime:
        years: 0
        months: 0
        days: 1

    start:
        year: 1
        month: 1
        days: 1

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0 --mca btl self,tcp
qsub_flags: -lother=hyperthread
collate_walltime: 0:05:00
collate_queue: express
