# PBS configuration
queue: express
project: v45
walltime: 0:10:00
jobname: access-cm_tiny
ncpus: 64

shortpath: /short/v45

# Model configuration
model: access
submodels:
    atmosphere:
        model: um
        exe: um7.3x
        input: um
        ncpus: 32

    ocean:
        model: mom
        exe: fms_ACCESS-CM.x
        input: mom
        ncpus: 16
        build:
            repository: https://github.com/nicholash/mom.git
            tag: mom-86-access-new
            path_to_build_command: exp
            command: './MOM_compile.csh --platform nci --type ACCESS-CM'
            exec_path: exec/nci/ACCESS-CM/

    ice:
        model: cice
        exe: cice_access-cm_360x300_6p.exe
        input: cice
        ncpus: 6
        build:
            command: 'make access-cm'

    coupler:
        model: oasis
        input: oasis_cm
        ncpus: 0

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0 -mca mtl ^mxm
