# PBS configuration
queue: normal
project: v45
walltime: 0:30:00
jobname: cnyf2
ncpus: 128

shortpath: /short/v45

# Model configuration
model: access
submodels:
    atmosphere:
        model: matm
        exe: matm_nt62.exe
        input: cnyf2_matm
        ncpus: 1

    ocean:
        model: mom
        exe: fms_ACCESS-OM.x
        input: cnyf2_mom
        ncpus: 120
        build:
            repository: https://github.com/nicholash/mom.git
            tag: mom-80-auscom
            command: 'cd exp && ./MOM_compile.csh --platform nci --type ACCESS-OM'
            exec_path: exec/nci/ACCESS-OM/

    ice:
        model: cice
        exe: cice_6p.exe
        input: cnyf2_cice
        ncpus: 6

    coupler:
        model: oasis
        input: cnyf2_oasis
        ncpus: 0

# Misc
stacksize: unlimited
