# PBS configuration
queue: normal
project: x77
walltime: 1:00:00
jobname: access-cm
ncpus: 144

shortpath: /short/v45

# Model configuration
model: access
submodels:
    atmosphere:
        model: um
        exe: um7.3x
        input: um
        ncpus: 96

    ocean:
        model: mom
        exe: fms_ACCESS-CM.x
        input: mom
        ncpus: 40
        build:
            path_to_build_command: exp
            repo: 'https://github.com/nicholash/mom.git'
            tag: 60-unit-testing
            command: './MOM_compile.csh --platform nci --type ACCESS-CM'
            exec_path: exec/nci/ACCESS-CM/

    ice:
        model: cice
        exe: cice_access-cm_360x300_6p.exe
        input: cice
        ncpus: 6
        build:
            exec_path: build_access-cm_360x300_6p
            command: 'make access-cm'

    coupler:
        model: oasis
        input: oasis_cm
        ncpus: 0

calendar:
    runtime:
        years: 0
        months: 1
        days: 0

    start:
        year: 1
        month: 1
        days: 1


# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0 -mca mtl ^mxm
