# PBS configuration
queue: express
project: x77
walltime: 00:05:00
jobname: om_360x300-tiny
ncpus: 64

shortpath: /short/v45

# Model configuration
model: access
submodels:
    - name: coupler
      model: oasis
      input: oasis_om
      ncpus: 0

    - name: atmosphere
      model: matm
      exe: matm_nt62.exe
      input: core2_nyf_matm
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM.x
      input: mom
      ncpus: 54
      build:
          path_to_build_command: exp
          command: './MOM_compile.csh --platform nci --type ACCESS-OM --unit-testing'
          exec_path: exec/nci/ACCESS-OM/

    - name: ice
      model: cice
      exe: cice_access-om_360x300_6p.exe
      input: cice
      ncpus: 6
      build:
          exec_path: build_access-om_360x300_6p
          command: './bld/build.sh nci access-om 360x300 unit_testing'

calendar:
    runtime:
        years: 0
        months: 0
        days: 1

    start:
        year: 1
        month: 1
        days: 1

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread
collate_walltime: 0:05:00
collate_queue: express
