# PBS configuration
queue: express
project: v45
walltime: 0:10:00
jobname: cm_1440x1080-unit_testing
ncpus: 1248

shortpath: /short/v45

# Model configuration
model: access
submodels:
    atmosphere:
        model: um
        exe: um7.3x
        input: um
        ncpus: 96

    ocean:
        model: mom
        exe: fms_ACCESS-CM.x
        input: mom_cm_1440x1080
        ncpus: 960
        build:
            path_to_build_command: exp
            command: './MOM_compile.csh --platform nci --type ACCESS-CM --unit_testing'
            exec_path: exec/nci/ACCESS-CM/

    ice:
        model: cice
        exe: cice_access-cm_1440x1080_192p.exe
        input: cice_cm_1440x1080
        ncpus: 192
        build:
            exec_path: build_access-cm_1440x1080_192p
            command: './bld/build.sh nci access-cm 1440x1080 unit_testing'

    coupler:
        model: oasis
        input: oasis_cm_1440x1080
        ncpus: 0

calendar:
    runtime:
        years: 0
        months: 1
        days: 0 

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0 --mca mtl ^mxm
collate_mem: 16GB
