# PBS configuration
queue: normal
project: v45
walltime: 1:00:00
jobname: om_1440x1080-unit_test
ncpus: 1168

shortpath: /short/v45

# Model configuration
model: access
submodels:
    atmosphere:
        model: matm
        exe: matm_nt62.exe
        input: /short/public/access/input/core2_nyf_matm
        ncpus: 1

    ocean:
        model: mom
        exe: fms_ACCESS-OM.x
        input: mom_om_1440x1080
        ncpus: 960
        build:
            repository: https://github.com/nicholash/mom.git
            tag: 60-unit-testing
            command: './MOM_compile.csh --platform nci --type ACCESS-OM --unit_testing'
            exec_path: exec/nci/ACCESS-OM/

    ice:
        model: cice
        exe: cice_access-om_1440x1080_192p.exe
        input: cice_om_1440x1080
        ncpus: 192
        build:
            command: './bld/build.sh nci access-om 1440x1080 unit_testing'
            exec_path: build_access-om_1440x1080_192p

    coupler:
        model: oasis
        input: oasis_om_1440x1080
        ncpus: 0


calendar:
    runtime:
        years: 0
        months: 0
        days: 1 

    start:
        years: 1
        months: 1
        days: 1 

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0 -mca mtl ^mxm

collate_mem: 6GB
