# PBS configuration
queue: normal
project: v45
walltime: 0:30:00
jobname: core2_nyf
ncpus: 144

shortpath: /short/v45

# Model configuration
model: access
submodels:
    atmosphere:
        model: um
        exe: um7.3.exe
        input: um
        ncpus: 96

    ocean:
        model: mom
        exe: fms_ACCESS-CM.x
        input: mom
        ncpus: 40
        build:
            command: 'cd exp && ./MOM_compile.csh --platform nci --type ACCESS-CM'
            exec_path: exec/nci/ACCESS-CM/

    ice:
        model: cice
        exe: cice_cm_6p.exe
        input: cice
        ncpus: 6

    coupler:
        model: oasis
        input: oasis
        ncpus: 0

# Misc
stacksize: unlimited
