# PBS configuration
queue: normal
project: v45
walltime: 04:00:00
jobname: core2_nyf
ncpus: 128

shortpath: /short/v45

# Model configuration
model: access
submodels:
    atmosphere:
        model: matm
        exe: matm_nt62.exe
        input: /home/599/nah599/v45/access/input/core2_nyf_matm
        ncpus: 1

    ocean:
        model: mom
        exe: fms_ACCESS-OM.x
        input: /home/599/nah599/v45/access/input/mom
        ncpus: 120
        build:
            repository: https://github.com/nicholash/mom.git
            command: 'cd exp && ./MOM_compile.csh --platform nci --type ACCESS-OM'
            exec_path: exec/nci/ACCESS-OM/

    ice:
        model: cice
        exe: cice_6p.exe
        input: /home/599/nah599/v45/access/input/cice
        ncpus: 6

    coupler:
        model: oasis
        input: /home/599/nah599/v45/access/input/oasis
        ncpus: 0

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0 -mca mtl ^mxm
