# PBS flags
queue: normal
project: v45
walltime: 5:00:00
ncpus: 960
mem: 1600GB
jobname: gfdl_nyf

# Model config
shortpath: /short/v45
model: mom
exe: fms_MOM5.1_SIS.x
input: gfdl_nyf_1080

# Misc
stacksize: unlimited

collate_walltime: 4:00:00
collate_mem: 8GB
qsub_flags: -lother=hyperthread
