# PBS configuration
queue: normal
project: x77
walltime: 03:00:00
jobname: core2_nyf
ncpus: 128

shortpath: /short/v45

# Model configuration
model: access
submodels:
    - name: coupler
      model: oasis
      input: oasis_om
      ncpus: 0

    - name: atmosphere
      model: matm
      exe: matm_nt62.exe
      input: core2_nyf_matm
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM.x
      input: mom
      ncpus: 120
      build:
          repository: https://github.com/nicholash/mom.git
          command: './MOM_compile.csh --platform nci --type ACCESS-OM'
          exec_path: exec/nci/ACCESS-OM/

    - name: ice
      model: cice
      exe: cice_access-om_360x300_6p.exe
      input: cice
      ncpus: 6


calendar:
    runtime:
        years: 0
        months: 12
        days: 0

    start:
        year: 1
        month: 1
        days: 1


# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread
